# Generated by Django 5.1.3 on 2024-11-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('file', models.FileField(upload_to='series/episodes')),
                ('episode_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='usermovielist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_movie_lists', to='Home.movie'),
        ),
        migrations.AlterField(
            model_name='usermovielist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='anime_posters/')),
                ('is_featured', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='anime_categories', to='Home.category')),
                ('episodes', models.ManyToManyField(related_name='anime_episodes', to='Home.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usermovielist',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_anime_lists', to='Home.anime'),
        ),
        migrations.CreateModel(
            name='AnimeEpisode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('file', models.FileField(upload_to='anime/episodes')),
                ('episode_number', models.PositiveIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_episodes', to='Home.anime')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('season_number', models.PositiveIntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series/seasons_posters/')),
                ('episodes', models.ManyToManyField(related_name='episode_seasons', to='Home.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_episodes', to='Home.season'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series_posters/')),
                ('is_featured', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='series_categories', to='Home.category')),
                ('seasons', models.ManyToManyField(related_name='season_series', to='Home.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_seasons', to='Home.series'),
        ),
        migrations.AddField(
            model_name='usermovielist',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_series_lists', to='Home.series'),
        ),
    ]
