# Generated by Django 5.1.3 on 2024-11-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cast_genre_movie_cast_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
