# Generated by Django 5.1.3 on 2024-11-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_movie_cast_delete_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profiles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
